### ISSUE TITLE
plotsize not work?

### ISSUE THREAD

**Issue by neizod** [dusadrian/venn#13]
Running on Jupyter Notebook, I can't control the plot size.

**Comment by dusadrian** [comment]
Hello @neizod,

Don't know exactly what I should do, since I cannot replicate your problem. I would suggest installing base R, and test if the behavior still holds.

Otherwise, it might be an issue related to how R works within a Jupyter Notebook (a Python based application, if I am not mistaken), and that is something outside the scope of package venn.

**Comment by neizod** [comment]
Thanks for your reply @dusadrian,

May be this is on Jupyter Notebook side, which I've solved it with `options(repr.plot.width=XXX, repr.plot.height=YYY)`.
