### ISSUE TITLE
intersections & components extraction

### ISSUE THREAD

**Issue by skim245** [dusadrian/venn#17]
@dusadrian I would like to extract both intersections in venn diagram and components corresponding to each overlaps. 

i.e. if I have a list of genes in group A-E, is there a way that I could extract a list of genes corresponding to each overlaps? 

Thank you in advance!

**Comment by mmahmoudian** [comment]
As far as I know, no it is not implemented in a way to extract those, but coding it is easy. I have made The following function to do this:

https://gist.github.com/mmahmoudian/ac5cfa9eee14624f25f894e80a96a748

Also if @dusadrian agrees, I can make a PR and add this function to this package.

**Comment by miraquddus** [comment]
@mmahmoudian It would be great if you could add the following additional functionality:
inputs:
a) No of sets: 1-7
b) Specify the color of the intersection: red / blue/ etc. 
c) Specify the outside of the figure: square rectangle or curved rectangle
d) Color of the box background: white / grey / black etc.

Outputs (as previous):
a) Print total area of the intersection
b) Print list of the components of the intersection

**Comment by mmahmoudian** [comment]
@miraquddus 
The function I posted is not suppose to plot a venn, but rather calculate and output the items in each zone of the venn. It is also dynamic, so that you can give it any arbitrary number of sets and it will calculate all the zones.

 For this reason, I do not understand how relevant your [a-d]&[ab] is. To me it seems you have posted an off-topic message. I suggest you to read the previous messages in the thread you are posting in, and if your question is irrelevant, create a new issue. Also remember that the general rule of thumb on Github and other VCS platform is to have one feature request per issue (although this depends on the main developer of the repository/project.

-------

Regardless, here is the answer to some of your points: with the `venn::venn()`, you can define all the colors you asked for via `col` and `zcolor` (your points b and d). You can also get the numbers in each zone easily by saving the invisible output of `venn::venn()` in a variable (answers your second point a):

```r
res <- venn::venn(your_list)
res
```

Your point c is addressed fully in #16.

**Comment by dusadrian** [comment]
@mmahmoudian as always, thank you very much for being so supportive.
Your code does not seem work on my computer, it uses a function called `lappend()` that is not in the base R and I have no idea where to take it from.

However, some of the things required by @skim245 might already be implemented in function `venn()`, that invisibly returns an object when the input is a list of elements.

Adapting the example list from Mehrad's code, this is what happens:

```r
set.seed(12345)
elements <- list(
    A = sample(x = letters, size = 20),
    B = sample(x = letters, size = 20),
    C = sample(x = letters, size = 20)
)

elements
# $A
#  [1] "n" "s" "p" "k" "b" "w" "f" "g" "j" "q" "x" "h" "y" "t" "a" "d" "o" "c" "l" "m"
# 
# $B
#  [1] "m" "t" "j" "w" "p" "v" "b" "i" "d" "h" "k" "f" "s" "e" "c" "a" "u" "z" "y" "q"
# 
# $C
#  [1] "c" "s" "m" "z" "q" "j" "k" "b" "l" "w" "x" "f" "v" "g" "u" "p" "r" "t" "i" "h"

obj <- venn(elements, ilabels = "counts")

obj
#       A B C counts
#       0 0 0      0
# C     0 0 1      1
# B     0 1 0      1
# B:C   0 1 1      4
# A     1 0 0      2
# A:C   1 0 1      3
# A:B   1 1 0      3
# A:B:C 1 1 1     12

attr(obj, "intersections")
# $C
# [1] "r"
# 
# $B
# [1] "e"
# 
# $`B:C`
# [1] "v" "i" "u" "z"
# 
# $A
# [1] "n" "o"
# 
# $`A:C`
# [1] "g" "x" "l"
# 
# $`A:B`
# [1] "y" "a" "d"
# 
# $`A:B:C`
#  [1] "s" "p" "k" "b" "w" "f" "j" "q" "h" "t" "c" "m"
```

**Comment by dusadrian** [comment]
I should probably add, that responding to these type of issues has only a purely theoretical interest. The same kind of requirements in multiple issues sounds suspiciously close to a homework, which I hope it is not the case here.

**Comment by mmahmoudian** [comment]
@dusadrian you are right, lapply is a function I have in my local personal package (soon will be part of a public package).

I never checked the attributes of the venn's object. Thanks for pointing it out 👍

**Comment by dusadrian** [comment]
If I am not mistaken, the attributes were introduced as part of [PR7](https://github.com/dusadrian/venn/issues/7), and they should be documented (if not, I will add the necessary description in the next version).
