### ISSUE TITLE
Specify the order of sets?

### ISSUE THREAD

**Issue by lucygarner** [dusadrian/venn#20]
Hi,

Is it possible to specify the order of the sets in the Venn diagram?

Best wishes,
Lucy

**Comment by dusadrian** [comment]
Hi @lucygarner,

If you mean the order in which the sets are printed on the diagram, there is the "snames" argument in the main function venn().

Otherwise, more details are needed about your particular need.

Best,
Adrian

**Comment by mmahmoudian** [comment]
If I understand the question correctly, it is already possible because the order is based on the input data:

```r
set.seed(12345)

a <- list(first = sample(x = letters, size = 20, replace = FALSE),
          second = sample(x = letters, size = 20, replace = FALSE),
          third = sample(x = letters, size = 20, replace = FALSE))

venn(a,
     zcolor = c(1,2,3),
     box = FALSE,
     ilcs = 2)
```

![image](https://user-images.githubusercontent.com/390889/221590871-d95fc060-d6f0-4ea0-9535-616d46a9fc83.png)


now if you define your order:

```r
my_order <- c(2,3,1)

venn(a[my_order],  #<-------------------------------------- specified order here
     zcolor = c(1,2,3)[my_order], #<----------------------- and here
     box = FALSE,
     ilcs = 2)
```

![image](https://user-images.githubusercontent.com/390889/221590933-ecfbda5d-3c7a-4e28-87e8-c3e371e9002b.png)

using the `sname` as @dusadrian suggested would change the order, but would keep the colors and other features in original (i.e provided) order:

```r
venn(a,
     zcolor = c(1,2,3),
     box = FALSE,
     snames = c("second", "third", "first"), #<------------ specified order here
     ilcs = 2)
```

![image](https://user-images.githubusercontent.com/390889/221591698-f4af842b-4ecc-4947-975a-7b1a523efb51.png)

**Comment by lucygarner** [comment]
Ok great, thank you both. I will give this a go.
