### ISSUE TITLE
Area proportional Venn diagram for 3-Circles

### ISSUE THREAD

**Issue by aaelony** [dusadrian/venn#25]
Awesome library! It would be even better if the circles were not the same size regardless of the counts.  Is there a way to scale the size of the circles proportionate to the counts and make it area proportional?  

Something akin to http://barc.wi.mit.edu/tools/venn/ ?

**Comment by dusadrian** [comment]
Thanks @aaelony, unfortunately not. What you want is an Euler diagram, as far as I am aware, while this package is only about the more restrictive Venn diagrams.
It would actually be very difficult to scale the shape sizes for more than three sets, and there are numerous ways to arrange them on a plot window. My shapes have fixed coordinates, which makes them easy to produce.
Best,
Adrian

**Comment by mmahmoudian** [comment]
@aaelony As @dusadrian well said, what you are after is Euler venn diagram. This was also something that at some point confused me too. I have been using [VennDiagram](https://cran.r-project.org/web/packages/VennDiagram/index.html) package for this [when I have to], although it is not as smooth as this [venn](https://cran.r-project.org/web/packages/venn/index.html) package.

I also found [eulerr](https://cran.r-project.org/web/packages/eulerr/index.html) and [venneuler](https://cran.r-project.org/web/packages/venneuler/index.html) packages today, although I have not tested them. As you can see in the vignette of {eulerr}, the readability of the plot can suffer is the overlapping zones are small. This is why I personally have stick to {venn} instead of any of these Euler venns. Also, please note that they both have extra dependencies (one Java and one C++) which might cause issues in the long run (especially the Java one).

**Comment by aaelony** [comment]
@mmahmoudian , thank-you for your comment; the `eulerr` package looks like what I am looking for.  
@dusadrian, thanks again for the authoring the `venn` package.
