### ISSUE TITLE
counts no longer printing on venn diagram

### ISSUE THREAD

**Issue by nataliegrima** [dusadrian/venn#26]
I tried to re-run a script written late last year that contained your venn function and noticed it is no longer printing any values within the venn diagram. The rest of the venn looks as expected. I am using the latest CRAN version (1.12) and am inputing a data frame of boolean values for 5 sets. I noticed the package was recently updated and was wondering if the usage has changed?

Arguments: `venn(venn_data, zcolor = "style", box = FALSE, ilcs = 1, sncs = 1)`

Head of `venn_data`:
A B C D E
1 0 0 0 0 
1 1 0 0 0 
1 0 1 1 1

**Comment by dusadrian** [comment]
Hi @nataliegrima,

There are several changes that involve printing the counts, and all of them are documented in the [ChangeLog](https://github.com/dusadrian/venn/blob/master/inst/ChangeLog) file.

One way to print the counts is to add the argument `ilabels = "counts"`. It was working back then because the (now obsolete) argument `counts` was `TRUE` by default.
