### ISSUE TITLE
How to add a title to the plot?

### ISSUE THREAD

**Issue by hsiaoyi0504** [dusadrian/venn#5]
As title, is there a method that I could add a title to the plot?

**Comment by dusadrian** [comment]
Not currently, I haven't really considered adding titles to Venn diagrams.
Part of the reason because (the plot being square) I wanted all available space on both horizontal and vertical, and partly because I don't really see a point using titles inside figures (any kind of figure, or plot) since it is so easy to add such titles in somewhere above or below the figure, using any typesetting software, thus preserving font uniformity (otherwise you need to make sure the font inside the figure is the same with the overall font of the text).

**Comment by mmahmoudian** [comment]
I use the function `title()` and it plays nice with `venn::venn()`. Basically I have a wrapper function to add titles/subtext and also reset the par.

**Comment by dusadrian** [comment]
Oh, that is nice, thanks a lot for the hint.
Could you perhaps post an example, so others can duplicate?

**Comment by hsiaoyi0504** [comment]
I finally figure it out. For other people who are interested in adding a title to the venn plot, do something like this:

``` R
venn_plot<-venn(
..., # some other arguments of the venn function
ggplot=TRUE
)
print(venn_plot + theme(plot.title = element_text(face="bold.italic", colour="black", size=14)) + ggtitle("whatever title you want"))
```

**Comment by mmahmoudian** [comment]
This is how I do it:

```r
library("venn")
set.seed(12345)
venn::venn(list(First = sample(x = letters, size = 20, replace = F),
                Second = sample(x = letters, size = 20, replace = F)),
           box = F,
           ilcs = 1.2,
           zcolor = c("#4477AA", "#CC6677"))
title(main = "The main title",
      sub = "Some sub text",
      line = -2)
```

which results in:
![image](https://user-images.githubusercontent.com/390889/113026920-3972a700-9192-11eb-8620-9b9915f479a9.png)


P.s: I always try to avoid ggplot2 and tidyverse

**Comment by dusadrian** [comment]
Thanks a lot.
(and I'm with you on trying to stay away from tidyverse and ggplot2, perfectly comfortable with the base R and graphics)

**Comment by hsiaoyi0504** [comment]
Thanks. Yes, it makes sense not to include another library unless you have already used them and would like to have uniform coding styles.
