### ISSUE TITLE
Some intersection areas aren't highlighted

### ISSUE THREAD

**Issue by supersayan** [dusadrian/venn#9]
First, the following code produces an error:
`venn("0 + 1")`
```
Error in polypath(polygons, rule = "evenodd", col = adjustcolor(zcolor[i], : Invalid graphics path
3.polypath(polygons, rule = "evenodd", col = adjustcolor(zcolor[i], alpha.f = opacity), border = NA)
2.plotRules(x, zcolor, ellipse, opacity, allborders = borders, box = box, gvenn = gvenn, ... = ...)
1.venn("0 + 1")
```
Though I've only tested up to size 3, any venn diagram where all the permutations of intersections of regions are specified produce the same error. i.e. `venn("01 + 10 + 00 + 11")` and `venn("111 + 001 + 010 + 100 + 110 + 101 + 011 + 000")` produce the same error.

Second, I'm not sure if this is intended, but specifying regions which are not "touching" will cause one of them to not be highlighted.
For example, the following will not highlight every region: (notation ~ABC/011 does not seem to make a difference)
- `venn("10 + 01")` : only 01 is highlighted, however `venn("01 + 10 + 11")` works as intended
- `venn("11 + 00")` : only 00 is highlighted, however `venn("11 + 00 + 01")` works as intended
- `venn("000 + 111")`, `venn("001 + 111")`, `venn("010 + 111")`, `venn("100 + 111")` : 111 is not highlighted
- for `venn("000 + 110")`, 110 will not highlight, and for `venn("100 + 111")`, 111 will not highlight.
- `venn("001 + 110")`, and `venn("001 + 111")` will only highlight 001, but `venn("001 + 110 + 111)" works as intended
- while `venn("001 + 011")` works, `venn("001 + 110")` does not.

The pattern seems to be that if there are two or more specified regions, a set of order n will only highlight if there is also a set of order n-1 with one set in common if it isn't the empty set, where order is the number of sets that region is true for. The behavior is a little weird and I might be explaining this poorly so I'll be willing to provide more info if needed.

**Comment by dusadrian** [comment]
Thanks for the issue, I should most likely update the documentation (and the code to trap those errors).

There have been some changes in functionality due to the relatively recent development in package [admisc](github.com/dusadrian/admisc) where users can use sums of products (SOP) expressions.

In such expressions, the `+` sign stands for a logical union and I think it might have to do with what happens in your examples. For instance, this works as intended:
`venn("0, 1")`
because the otherwise tried union `0 + 1` is simplified to the unity.

I'll try to see exactly why some intersection areas are not highlighted, but if your purpose is to highlight specific intersections then you can use a comma `,` sign instead of the logical union `+`, for instance:
`venn("000, 111")`
should work as expected.

**Comment by supersayan** [comment]
Ah, I understand. Sorry for the confusion.
